### ISSUE TITLE
Rate Limit for Arachni Scans

### ISSUE THREAD

**Issue by MartinLang1** [secureCodeBox/scanner-webapplication-arachni#2]
As a user I would like to reduce the number of requests per second during my scans so that they won't affect the performance of my application and the scanner won't be blocked by a WAF.

Arachni provides the options to set the `browser-cluster-pool-size` and the `http-request-concurrency`. Additionally, the rate_limiter plugin provides the option `requests_per_second` to set a maximum for the requests per second.

In my target definition (used for Arachni Scans) I would like to configure something like this:
```
[
    {
        "name": "Arachni BodgeIt Scan",
        "location": "http://bodgeit:8080/bodgeit/",
        "attributes": {
            "ARACHNI_RATE_LIMITS": {
                browserClusterPoolSize: 1,
                httpRequestConcurrency: 2,
                requestsPerSecond: 3
             }
        }
    }
]
```

**Comment by rseedorff** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Archni Scanner um ein RATE-Limit Feature erweitern](https://trello.com/c/cJrP6Ism/203-archni-scanner-um-ein-rate-limit-feature-erweitern)

**Comment by J12934** [comment]
This issue has been implemented.
